# Site settings
title: Ev Blurbs
email: evan@createinform.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://evblurbs.github.io"
username: evblurbs
twitter: ev_blurbs

# Build settings
markdown: kramdown
permalink: pretty
